language: c

before_install:
    - test -n $CC && unset CC
    # apt-package-whitelist can be found in
    # https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
    - sudo add-apt-repository ppa:dns/gnu -y
    - sudo apt-get update -qq
    - sudo apt-get install -y gfortran
    - sudo apt-get install -y mpich2
    - sudo apt-get install --only-upgrade autoconf
    - sudo apt-get install --only-upgrade automake
    - sudo apt-get install --only-upgrade libtool
    # string substitute for SVN keyword LastChangedDate
    # Below is for Redhat
    # - DateStr=`stat -f "%Sm" -t "%F %T %z (%a, %d %b %Y)" configure.ac` ; sed -e "s/LastChangedDate/LastChangedDate: $DateStr /g" -i "" configure
    # Below is for Ubuntu
    # - DateStr=`date -r configure.ac +"%F %T %z (%a, %d %b %Y)"` ; sed -e "s/LastChangedDate/LastChangedDate $DateStr /g" -i configure

install:
    - autoconf --version
    - automake --version
    - libtool --version
    - autoreconf -if

script:
    # continue the above "build_command" for static library only (default)
    - make -s V=1 LIBTOOLFLAGS=--silent distcheck DISTCHECK_CONFIGURE_FLAGS=--silent
    - make -s distclean
    # build both static and shared libraries
    - ./configure --silent --enable-shared LDFLAGS="-Wl,--allow-shlib-undefined"
    - make -s V=1 LIBTOOLFLAGS=--silent tests
    - make -s V=1 LIBTOOLFLAGS=--silent distcheck DISTCHECK_CONFIGURE_FLAGS="--silent --enable-shared LDFLAGS='-Wl,--allow-shlib-undefined'"
    - make -s distclean
    # build shared library only
    # - ./configure --silent --enable-shared --disable-static LDFLAGS="-Wl,--allow-shlib-undefined"
    # - make -s V=1 LIBTOOLFLAGS=--silent tests
    # - make -s V=1 LIBTOOLFLAGS=--silent distcheck DISTCHECK_CONFIGURE_FLAGS="--silent --enable-shared --disable-static LDFLAGS='-Wl,--allow-shlib-undefined'"
    # - make -s distclean

after_failure:
    - cat /home/travis/build/wkliao/parallel-netcdf/cov-int/build-log.txt
    - cat ./config.log

notifications:
    email: 
        - kai-yuanhou2020@u.northwestern.edu
