/* Do not edit this file. It is produced from the corresponding .m4 source */
/*********************************************************************
 *
 *  Copyright (C) 2017, Northwestern University and Argonne National Laboratory
 *  See COPYRIGHT notice in top-level directory.
 *
 *********************************************************************/
/* $Id: transpose.c 3078 2017-05-29 22:46:50Z wkliao $ */

#include <stdio.h>
#include <stdlib.h>
#include <string.h> /* strcpy(), strncpy() */
#include <unistd.h> /* getopt() */
#include <libgen.h> /* basename() */
#include <mpi.h>
#include <pnetcdf.h>

#include <testutils.h>

#define NDIMS 3
#define LEN   2




#define text char
#ifndef schar
#define schar signed char
#endif
#ifndef uchar
#define uchar unsigned char
#endif
#ifndef ushort
#define ushort unsigned short
#endif
#ifndef uint
#define uint unsigned int
#endif
#ifndef longlong
#define longlong long long
#endif
#ifndef ulonglong
#define ulonglong unsigned long long
#endif


static int
non_blocking_put_schar(int         rank,
                int         ncid,
                int        *dimids,
                MPI_Offset *start,
                MPI_Offset *count,
                MPI_Offset *startS,
                MPI_Offset *countS,
                MPI_Offset *stride,
                MPI_Offset *startM,
                MPI_Offset *countM,
                MPI_Offset *imap,
                double     *buf)
{
    int err, nerrs=0;
    int var1_id, vara_id, vars_id, varm_id;
    int dimid, dimidsT[NDIMS];
    MPI_Offset start1;

    /* re-enter define mode, so we can add more variables */
    err = ncmpi_redef(ncid); CHECK_ERR
    err = ncmpi_inq_dimid(ncid, "nprocs", &dimid); CHECK_ERR
    err = ncmpi_def_var(ncid, "var1_schar", NC_BYTE,     1, &dimid, &var1_id); CHECK_ERR
    err = ncmpi_def_var(ncid, "vara_schar", NC_BYTE, NDIMS, dimids, &vara_id); CHECK_ERR
    err = ncmpi_def_var(ncid, "vars_schar", NC_BYTE, NDIMS, dimids, &vars_id); CHECK_ERR

    /* define variable with transposed file layout: ZYX -> YXZ */
    dimidsT[0] = dimids[1]; dimidsT[1] = dimids[2]; dimidsT[2] = dimids[0];
    err = ncmpi_def_var(ncid, "varm_schar", NC_BYTE, NDIMS, dimidsT, &varm_id); CHECK_ERR

    /* exit the define mode */
    err = ncmpi_enddef(ncid); CHECK_ERR

    /* write the whole variable in parallel */
    start1 = rank;
    err = ncmpi_iput_var1_double(ncid, var1_id, &start1, buf, NULL); CHECK_ERR

    err = ncmpi_iput_vara_double(ncid, vara_id, start, count, buf, NULL); CHECK_ERR

    err = ncmpi_iput_vars_double(ncid, vars_id, startS, countS, stride, buf, NULL);
    CHECK_ERR

    err = ncmpi_iput_varm_double(ncid, varm_id, startM, countM, NULL, imap, buf, NULL);
    CHECK_ERR
    
    /* wait for all input */
    err = ncmpi_wait_all(ncid, NC_REQ_ALL, NULL, NULL);
    CHECK_ERR

    return nerrs;
}
static int
non_blocking_put_uchar(int         rank,
                int         ncid,
                int        *dimids,
                MPI_Offset *start,
                MPI_Offset *count,
                MPI_Offset *startS,
                MPI_Offset *countS,
                MPI_Offset *stride,
                MPI_Offset *startM,
                MPI_Offset *countM,
                MPI_Offset *imap,
                double     *buf)
{
    int err, nerrs=0;
    int var1_id, vara_id, vars_id, varm_id;
    int dimid, dimidsT[NDIMS];
    MPI_Offset start1;

    /* re-enter define mode, so we can add more variables */
    err = ncmpi_redef(ncid); CHECK_ERR
    err = ncmpi_inq_dimid(ncid, "nprocs", &dimid); CHECK_ERR
    err = ncmpi_def_var(ncid, "var1_uchar", NC_UBYTE,     1, &dimid, &var1_id); CHECK_ERR
    err = ncmpi_def_var(ncid, "vara_uchar", NC_UBYTE, NDIMS, dimids, &vara_id); CHECK_ERR
    err = ncmpi_def_var(ncid, "vars_uchar", NC_UBYTE, NDIMS, dimids, &vars_id); CHECK_ERR

    /* define variable with transposed file layout: ZYX -> YXZ */
    dimidsT[0] = dimids[1]; dimidsT[1] = dimids[2]; dimidsT[2] = dimids[0];
    err = ncmpi_def_var(ncid, "varm_uchar", NC_UBYTE, NDIMS, dimidsT, &varm_id); CHECK_ERR

    /* exit the define mode */
    err = ncmpi_enddef(ncid); CHECK_ERR

    /* write the whole variable in parallel */
    start1 = rank;
    err = ncmpi_iput_var1_double(ncid, var1_id, &start1, buf, NULL); CHECK_ERR

    err = ncmpi_iput_vara_double(ncid, vara_id, start, count, buf, NULL); CHECK_ERR

    err = ncmpi_iput_vars_double(ncid, vars_id, startS, countS, stride, buf, NULL);
    CHECK_ERR

    err = ncmpi_iput_varm_double(ncid, varm_id, startM, countM, NULL, imap, buf, NULL);
    CHECK_ERR
    
    /* wait for all input */
    err = ncmpi_wait_all(ncid, NC_REQ_ALL, NULL, NULL);
    CHECK_ERR

    return nerrs;
}
static int
non_blocking_put_short(int         rank,
                int         ncid,
                int        *dimids,
                MPI_Offset *start,
                MPI_Offset *count,
                MPI_Offset *startS,
                MPI_Offset *countS,
                MPI_Offset *stride,
                MPI_Offset *startM,
                MPI_Offset *countM,
                MPI_Offset *imap,
                double     *buf)
{
    int err, nerrs=0;
    int var1_id, vara_id, vars_id, varm_id;
    int dimid, dimidsT[NDIMS];
    MPI_Offset start1;

    /* re-enter define mode, so we can add more variables */
    err = ncmpi_redef(ncid); CHECK_ERR
    err = ncmpi_inq_dimid(ncid, "nprocs", &dimid); CHECK_ERR
    err = ncmpi_def_var(ncid, "var1_short", NC_SHORT,     1, &dimid, &var1_id); CHECK_ERR
    err = ncmpi_def_var(ncid, "vara_short", NC_SHORT, NDIMS, dimids, &vara_id); CHECK_ERR
    err = ncmpi_def_var(ncid, "vars_short", NC_SHORT, NDIMS, dimids, &vars_id); CHECK_ERR

    /* define variable with transposed file layout: ZYX -> YXZ */
    dimidsT[0] = dimids[1]; dimidsT[1] = dimids[2]; dimidsT[2] = dimids[0];
    err = ncmpi_def_var(ncid, "varm_short", NC_SHORT, NDIMS, dimidsT, &varm_id); CHECK_ERR

    /* exit the define mode */
    err = ncmpi_enddef(ncid); CHECK_ERR

    /* write the whole variable in parallel */
    start1 = rank;
    err = ncmpi_iput_var1_double(ncid, var1_id, &start1, buf, NULL); CHECK_ERR

    err = ncmpi_iput_vara_double(ncid, vara_id, start, count, buf, NULL); CHECK_ERR

    err = ncmpi_iput_vars_double(ncid, vars_id, startS, countS, stride, buf, NULL);
    CHECK_ERR

    err = ncmpi_iput_varm_double(ncid, varm_id, startM, countM, NULL, imap, buf, NULL);
    CHECK_ERR
    
    /* wait for all input */
    err = ncmpi_wait_all(ncid, NC_REQ_ALL, NULL, NULL);
    CHECK_ERR

    return nerrs;
}
static int
non_blocking_put_ushort(int         rank,
                int         ncid,
                int        *dimids,
                MPI_Offset *start,
                MPI_Offset *count,
                MPI_Offset *startS,
                MPI_Offset *countS,
                MPI_Offset *stride,
                MPI_Offset *startM,
                MPI_Offset *countM,
                MPI_Offset *imap,
                double     *buf)
{
    int err, nerrs=0;
    int var1_id, vara_id, vars_id, varm_id;
    int dimid, dimidsT[NDIMS];
    MPI_Offset start1;

    /* re-enter define mode, so we can add more variables */
    err = ncmpi_redef(ncid); CHECK_ERR
    err = ncmpi_inq_dimid(ncid, "nprocs", &dimid); CHECK_ERR
    err = ncmpi_def_var(ncid, "var1_ushort", NC_USHORT,     1, &dimid, &var1_id); CHECK_ERR
    err = ncmpi_def_var(ncid, "vara_ushort", NC_USHORT, NDIMS, dimids, &vara_id); CHECK_ERR
    err = ncmpi_def_var(ncid, "vars_ushort", NC_USHORT, NDIMS, dimids, &vars_id); CHECK_ERR

    /* define variable with transposed file layout: ZYX -> YXZ */
    dimidsT[0] = dimids[1]; dimidsT[1] = dimids[2]; dimidsT[2] = dimids[0];
    err = ncmpi_def_var(ncid, "varm_ushort", NC_USHORT, NDIMS, dimidsT, &varm_id); CHECK_ERR

    /* exit the define mode */
    err = ncmpi_enddef(ncid); CHECK_ERR

    /* write the whole variable in parallel */
    start1 = rank;
    err = ncmpi_iput_var1_double(ncid, var1_id, &start1, buf, NULL); CHECK_ERR

    err = ncmpi_iput_vara_double(ncid, vara_id, start, count, buf, NULL); CHECK_ERR

    err = ncmpi_iput_vars_double(ncid, vars_id, startS, countS, stride, buf, NULL);
    CHECK_ERR

    err = ncmpi_iput_varm_double(ncid, varm_id, startM, countM, NULL, imap, buf, NULL);
    CHECK_ERR
    
    /* wait for all input */
    err = ncmpi_wait_all(ncid, NC_REQ_ALL, NULL, NULL);
    CHECK_ERR

    return nerrs;
}
static int
non_blocking_put_int(int         rank,
                int         ncid,
                int        *dimids,
                MPI_Offset *start,
                MPI_Offset *count,
                MPI_Offset *startS,
                MPI_Offset *countS,
                MPI_Offset *stride,
                MPI_Offset *startM,
                MPI_Offset *countM,
                MPI_Offset *imap,
                double     *buf)
{
    int err, nerrs=0;
    int var1_id, vara_id, vars_id, varm_id;
    int dimid, dimidsT[NDIMS];
    MPI_Offset start1;

    /* re-enter define mode, so we can add more variables */
    err = ncmpi_redef(ncid); CHECK_ERR
    err = ncmpi_inq_dimid(ncid, "nprocs", &dimid); CHECK_ERR
    err = ncmpi_def_var(ncid, "var1_int", NC_INT,     1, &dimid, &var1_id); CHECK_ERR
    err = ncmpi_def_var(ncid, "vara_int", NC_INT, NDIMS, dimids, &vara_id); CHECK_ERR
    err = ncmpi_def_var(ncid, "vars_int", NC_INT, NDIMS, dimids, &vars_id); CHECK_ERR

    /* define variable with transposed file layout: ZYX -> YXZ */
    dimidsT[0] = dimids[1]; dimidsT[1] = dimids[2]; dimidsT[2] = dimids[0];
    err = ncmpi_def_var(ncid, "varm_int", NC_INT, NDIMS, dimidsT, &varm_id); CHECK_ERR

    /* exit the define mode */
    err = ncmpi_enddef(ncid); CHECK_ERR

    /* write the whole variable in parallel */
    start1 = rank;
    err = ncmpi_iput_var1_double(ncid, var1_id, &start1, buf, NULL); CHECK_ERR

    err = ncmpi_iput_vara_double(ncid, vara_id, start, count, buf, NULL); CHECK_ERR

    err = ncmpi_iput_vars_double(ncid, vars_id, startS, countS, stride, buf, NULL);
    CHECK_ERR

    err = ncmpi_iput_varm_double(ncid, varm_id, startM, countM, NULL, imap, buf, NULL);
    CHECK_ERR
    
    /* wait for all input */
    err = ncmpi_wait_all(ncid, NC_REQ_ALL, NULL, NULL);
    CHECK_ERR

    return nerrs;
}
static int
non_blocking_put_uint(int         rank,
                int         ncid,
                int        *dimids,
                MPI_Offset *start,
                MPI_Offset *count,
                MPI_Offset *startS,
                MPI_Offset *countS,
                MPI_Offset *stride,
                MPI_Offset *startM,
                MPI_Offset *countM,
                MPI_Offset *imap,
                double     *buf)
{
    int err, nerrs=0;
    int var1_id, vara_id, vars_id, varm_id;
    int dimid, dimidsT[NDIMS];
    MPI_Offset start1;

    /* re-enter define mode, so we can add more variables */
    err = ncmpi_redef(ncid); CHECK_ERR
    err = ncmpi_inq_dimid(ncid, "nprocs", &dimid); CHECK_ERR
    err = ncmpi_def_var(ncid, "var1_uint", NC_UINT,     1, &dimid, &var1_id); CHECK_ERR
    err = ncmpi_def_var(ncid, "vara_uint", NC_UINT, NDIMS, dimids, &vara_id); CHECK_ERR
    err = ncmpi_def_var(ncid, "vars_uint", NC_UINT, NDIMS, dimids, &vars_id); CHECK_ERR

    /* define variable with transposed file layout: ZYX -> YXZ */
    dimidsT[0] = dimids[1]; dimidsT[1] = dimids[2]; dimidsT[2] = dimids[0];
    err = ncmpi_def_var(ncid, "varm_uint", NC_UINT, NDIMS, dimidsT, &varm_id); CHECK_ERR

    /* exit the define mode */
    err = ncmpi_enddef(ncid); CHECK_ERR

    /* write the whole variable in parallel */
    start1 = rank;
    err = ncmpi_iput_var1_double(ncid, var1_id, &start1, buf, NULL); CHECK_ERR

    err = ncmpi_iput_vara_double(ncid, vara_id, start, count, buf, NULL); CHECK_ERR

    err = ncmpi_iput_vars_double(ncid, vars_id, startS, countS, stride, buf, NULL);
    CHECK_ERR

    err = ncmpi_iput_varm_double(ncid, varm_id, startM, countM, NULL, imap, buf, NULL);
    CHECK_ERR
    
    /* wait for all input */
    err = ncmpi_wait_all(ncid, NC_REQ_ALL, NULL, NULL);
    CHECK_ERR

    return nerrs;
}
static int
non_blocking_put_long(int         rank,
                int         ncid,
                int        *dimids,
                MPI_Offset *start,
                MPI_Offset *count,
                MPI_Offset *startS,
                MPI_Offset *countS,
                MPI_Offset *stride,
                MPI_Offset *startM,
                MPI_Offset *countM,
                MPI_Offset *imap,
                double     *buf)
{
    int err, nerrs=0;
    int var1_id, vara_id, vars_id, varm_id;
    int dimid, dimidsT[NDIMS];
    MPI_Offset start1;

    /* re-enter define mode, so we can add more variables */
    err = ncmpi_redef(ncid); CHECK_ERR
    err = ncmpi_inq_dimid(ncid, "nprocs", &dimid); CHECK_ERR
    err = ncmpi_def_var(ncid, "var1_long", NC_LONG,     1, &dimid, &var1_id); CHECK_ERR
    err = ncmpi_def_var(ncid, "vara_long", NC_LONG, NDIMS, dimids, &vara_id); CHECK_ERR
    err = ncmpi_def_var(ncid, "vars_long", NC_LONG, NDIMS, dimids, &vars_id); CHECK_ERR

    /* define variable with transposed file layout: ZYX -> YXZ */
    dimidsT[0] = dimids[1]; dimidsT[1] = dimids[2]; dimidsT[2] = dimids[0];
    err = ncmpi_def_var(ncid, "varm_long", NC_LONG, NDIMS, dimidsT, &varm_id); CHECK_ERR

    /* exit the define mode */
    err = ncmpi_enddef(ncid); CHECK_ERR

    /* write the whole variable in parallel */
    start1 = rank;
    err = ncmpi_iput_var1_double(ncid, var1_id, &start1, buf, NULL); CHECK_ERR

    err = ncmpi_iput_vara_double(ncid, vara_id, start, count, buf, NULL); CHECK_ERR

    err = ncmpi_iput_vars_double(ncid, vars_id, startS, countS, stride, buf, NULL);
    CHECK_ERR

    err = ncmpi_iput_varm_double(ncid, varm_id, startM, countM, NULL, imap, buf, NULL);
    CHECK_ERR
    
    /* wait for all input */
    err = ncmpi_wait_all(ncid, NC_REQ_ALL, NULL, NULL);
    CHECK_ERR

    return nerrs;
}
static int
non_blocking_put_float(int         rank,
                int         ncid,
                int        *dimids,
                MPI_Offset *start,
                MPI_Offset *count,
                MPI_Offset *startS,
                MPI_Offset *countS,
                MPI_Offset *stride,
                MPI_Offset *startM,
                MPI_Offset *countM,
                MPI_Offset *imap,
                double     *buf)
{
    int err, nerrs=0;
    int var1_id, vara_id, vars_id, varm_id;
    int dimid, dimidsT[NDIMS];
    MPI_Offset start1;

    /* re-enter define mode, so we can add more variables */
    err = ncmpi_redef(ncid); CHECK_ERR
    err = ncmpi_inq_dimid(ncid, "nprocs", &dimid); CHECK_ERR
    err = ncmpi_def_var(ncid, "var1_float", NC_FLOAT,     1, &dimid, &var1_id); CHECK_ERR
    err = ncmpi_def_var(ncid, "vara_float", NC_FLOAT, NDIMS, dimids, &vara_id); CHECK_ERR
    err = ncmpi_def_var(ncid, "vars_float", NC_FLOAT, NDIMS, dimids, &vars_id); CHECK_ERR

    /* define variable with transposed file layout: ZYX -> YXZ */
    dimidsT[0] = dimids[1]; dimidsT[1] = dimids[2]; dimidsT[2] = dimids[0];
    err = ncmpi_def_var(ncid, "varm_float", NC_FLOAT, NDIMS, dimidsT, &varm_id); CHECK_ERR

    /* exit the define mode */
    err = ncmpi_enddef(ncid); CHECK_ERR

    /* write the whole variable in parallel */
    start1 = rank;
    err = ncmpi_iput_var1_double(ncid, var1_id, &start1, buf, NULL); CHECK_ERR

    err = ncmpi_iput_vara_double(ncid, vara_id, start, count, buf, NULL); CHECK_ERR

    err = ncmpi_iput_vars_double(ncid, vars_id, startS, countS, stride, buf, NULL);
    CHECK_ERR

    err = ncmpi_iput_varm_double(ncid, varm_id, startM, countM, NULL, imap, buf, NULL);
    CHECK_ERR
    
    /* wait for all input */
    err = ncmpi_wait_all(ncid, NC_REQ_ALL, NULL, NULL);
    CHECK_ERR

    return nerrs;
}
static int
non_blocking_put_double(int         rank,
                int         ncid,
                int        *dimids,
                MPI_Offset *start,
                MPI_Offset *count,
                MPI_Offset *startS,
                MPI_Offset *countS,
                MPI_Offset *stride,
                MPI_Offset *startM,
                MPI_Offset *countM,
                MPI_Offset *imap,
                double     *buf)
{
    int err, nerrs=0;
    int var1_id, vara_id, vars_id, varm_id;
    int dimid, dimidsT[NDIMS];
    MPI_Offset start1;

    /* re-enter define mode, so we can add more variables */
    err = ncmpi_redef(ncid); CHECK_ERR
    err = ncmpi_inq_dimid(ncid, "nprocs", &dimid); CHECK_ERR
    err = ncmpi_def_var(ncid, "var1_double", NC_DOUBLE,     1, &dimid, &var1_id); CHECK_ERR
    err = ncmpi_def_var(ncid, "vara_double", NC_DOUBLE, NDIMS, dimids, &vara_id); CHECK_ERR
    err = ncmpi_def_var(ncid, "vars_double", NC_DOUBLE, NDIMS, dimids, &vars_id); CHECK_ERR

    /* define variable with transposed file layout: ZYX -> YXZ */
    dimidsT[0] = dimids[1]; dimidsT[1] = dimids[2]; dimidsT[2] = dimids[0];
    err = ncmpi_def_var(ncid, "varm_double", NC_DOUBLE, NDIMS, dimidsT, &varm_id); CHECK_ERR

    /* exit the define mode */
    err = ncmpi_enddef(ncid); CHECK_ERR

    /* write the whole variable in parallel */
    start1 = rank;
    err = ncmpi_iput_var1_double(ncid, var1_id, &start1, buf, NULL); CHECK_ERR

    err = ncmpi_iput_vara_double(ncid, vara_id, start, count, buf, NULL); CHECK_ERR

    err = ncmpi_iput_vars_double(ncid, vars_id, startS, countS, stride, buf, NULL);
    CHECK_ERR

    err = ncmpi_iput_varm_double(ncid, varm_id, startM, countM, NULL, imap, buf, NULL);
    CHECK_ERR
    
    /* wait for all input */
    err = ncmpi_wait_all(ncid, NC_REQ_ALL, NULL, NULL);
    CHECK_ERR

    return nerrs;
}
static int
non_blocking_put_longlong(int         rank,
                int         ncid,
                int        *dimids,
                MPI_Offset *start,
                MPI_Offset *count,
                MPI_Offset *startS,
                MPI_Offset *countS,
                MPI_Offset *stride,
                MPI_Offset *startM,
                MPI_Offset *countM,
                MPI_Offset *imap,
                double     *buf)
{
    int err, nerrs=0;
    int var1_id, vara_id, vars_id, varm_id;
    int dimid, dimidsT[NDIMS];
    MPI_Offset start1;

    /* re-enter define mode, so we can add more variables */
    err = ncmpi_redef(ncid); CHECK_ERR
    err = ncmpi_inq_dimid(ncid, "nprocs", &dimid); CHECK_ERR
    err = ncmpi_def_var(ncid, "var1_longlong", NC_INT64,     1, &dimid, &var1_id); CHECK_ERR
    err = ncmpi_def_var(ncid, "vara_longlong", NC_INT64, NDIMS, dimids, &vara_id); CHECK_ERR
    err = ncmpi_def_var(ncid, "vars_longlong", NC_INT64, NDIMS, dimids, &vars_id); CHECK_ERR

    /* define variable with transposed file layout: ZYX -> YXZ */
    dimidsT[0] = dimids[1]; dimidsT[1] = dimids[2]; dimidsT[2] = dimids[0];
    err = ncmpi_def_var(ncid, "varm_longlong", NC_INT64, NDIMS, dimidsT, &varm_id); CHECK_ERR

    /* exit the define mode */
    err = ncmpi_enddef(ncid); CHECK_ERR

    /* write the whole variable in parallel */
    start1 = rank;
    err = ncmpi_iput_var1_double(ncid, var1_id, &start1, buf, NULL); CHECK_ERR

    err = ncmpi_iput_vara_double(ncid, vara_id, start, count, buf, NULL); CHECK_ERR

    err = ncmpi_iput_vars_double(ncid, vars_id, startS, countS, stride, buf, NULL);
    CHECK_ERR

    err = ncmpi_iput_varm_double(ncid, varm_id, startM, countM, NULL, imap, buf, NULL);
    CHECK_ERR
    
    /* wait for all input */
    err = ncmpi_wait_all(ncid, NC_REQ_ALL, NULL, NULL);
    CHECK_ERR

    return nerrs;
}
static int
non_blocking_put_ulonglong(int         rank,
                int         ncid,
                int        *dimids,
                MPI_Offset *start,
                MPI_Offset *count,
                MPI_Offset *startS,
                MPI_Offset *countS,
                MPI_Offset *stride,
                MPI_Offset *startM,
                MPI_Offset *countM,
                MPI_Offset *imap,
                double     *buf)
{
    int err, nerrs=0;
    int var1_id, vara_id, vars_id, varm_id;
    int dimid, dimidsT[NDIMS];
    MPI_Offset start1;

    /* re-enter define mode, so we can add more variables */
    err = ncmpi_redef(ncid); CHECK_ERR
    err = ncmpi_inq_dimid(ncid, "nprocs", &dimid); CHECK_ERR
    err = ncmpi_def_var(ncid, "var1_ulonglong", NC_UINT64,     1, &dimid, &var1_id); CHECK_ERR
    err = ncmpi_def_var(ncid, "vara_ulonglong", NC_UINT64, NDIMS, dimids, &vara_id); CHECK_ERR
    err = ncmpi_def_var(ncid, "vars_ulonglong", NC_UINT64, NDIMS, dimids, &vars_id); CHECK_ERR

    /* define variable with transposed file layout: ZYX -> YXZ */
    dimidsT[0] = dimids[1]; dimidsT[1] = dimids[2]; dimidsT[2] = dimids[0];
    err = ncmpi_def_var(ncid, "varm_ulonglong", NC_UINT64, NDIMS, dimidsT, &varm_id); CHECK_ERR

    /* exit the define mode */
    err = ncmpi_enddef(ncid); CHECK_ERR

    /* write the whole variable in parallel */
    start1 = rank;
    err = ncmpi_iput_var1_double(ncid, var1_id, &start1, buf, NULL); CHECK_ERR

    err = ncmpi_iput_vara_double(ncid, vara_id, start, count, buf, NULL); CHECK_ERR

    err = ncmpi_iput_vars_double(ncid, vars_id, startS, countS, stride, buf, NULL);
    CHECK_ERR

    err = ncmpi_iput_varm_double(ncid, varm_id, startM, countM, NULL, imap, buf, NULL);
    CHECK_ERR
    
    /* wait for all input */
    err = ncmpi_wait_all(ncid, NC_REQ_ALL, NULL, NULL);
    CHECK_ERR

    return nerrs;
}



/*----< main() >------------------------------------------------------------*/
int main(int argc, char **argv)
{
    extern int optind;
    char filename[256], fname[512];
    int i, j, k, rank, nprocs, ncid, bufsize, err, nerrs=0, cmode;
    int psize[NDIMS], dimids[NDIMS], dim_rank[NDIMS];
    double *buf;
    MPI_Offset gsize[NDIMS], stride[NDIMS], imap[NDIMS];
    MPI_Offset start[NDIMS], count[NDIMS];
    MPI_Offset startS[NDIMS], countS[NDIMS];
    MPI_Offset startM[NDIMS], countM[NDIMS];
    MPI_Info info;

    MPI_Init(&argc,&argv);
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);
    MPI_Comm_size(MPI_COMM_WORLD, &nprocs);

    if (argc > 2) {
        if (!rank) printf("Usage: %s [filename]\n",argv[0]);
        MPI_Finalize();
        return 1;
    }
    if (argc == 2) snprintf(filename, 256, "%s", argv[1]);
    else           strcpy(filename, "testfile.nc");
    MPI_Bcast(filename, 256, MPI_CHAR, 0, MPI_COMM_WORLD);

    if (rank == 0) {
        char *cmd_str = (char*)malloc(strlen(argv[0]) + 256);
        sprintf(cmd_str, "*** TESTING C   %s for all kinds put APIs ", basename(argv[0]));
        printf("%-66s ------ ", cmd_str); fflush(stdout);
        free(cmd_str);
    }

    /* calculate number of processes along each dimension */
    for (i=0; i<NDIMS; i++) psize[i] = 0;
    MPI_Dims_create(nprocs, NDIMS, psize);

    /* for each MPI rank, find its local rank IDs along each dimension in
     * dim_rank[] */
    int lower_dims=1;
    for (i=NDIMS-1; i>=0; i--) {
        dim_rank[i] = rank / lower_dims % psize[i];
        lower_dims *= psize[i];
    }

    /* calculate gsize[], global array sizes and set arguments start and count
     * for vara APIs */
    bufsize = 1;
    for (i=0; i<NDIMS; i++) {
        gsize[i]  = (MPI_Offset)LEN * psize[i];    /* global array size */
        start[i]  = (MPI_Offset)LEN * dim_rank[i]; /* start indices */
        count[i]  = (MPI_Offset)LEN;               /* array elements */
        bufsize  *= LEN;
    }

    /* allocate buffer and initialize with contiguous numbers */
    buf = (double *) malloc(bufsize * sizeof(double));
    for (k=0; k<count[0]; k++)
    for (j=0; j<count[1]; j++)
    for (i=0; i<count[2]; i++)
        buf[k*count[1]*count[2] +
                     j*count[2] + i] = (start[0]+k)*gsize[1]*gsize[2]
                                     + (start[1]+j)*gsize[2]
                                     + (start[2]+i); // + 1000*(rank+1);

    /* set an MPI-IO hint to disable file offset alignment for fixed-size
     * variables */
    MPI_Info_create(&info);
    MPI_Info_set(info, "nc_var_align_size", "1");

    /* set arguments start, count, stride for vars APIs */
    for (i=0; i<NDIMS; i++) {
        startS[i] = dim_rank[i];
        countS[i] = gsize[i] / psize[i];
        stride[i] = psize[i];
    }

    /* ZYX -> YXZ: (this is borrowed from examples/C/transpose.c */
    imap[1] = 1; imap[0] = count[2]; imap[2] = count[1]*count[2];
    startM[0] = start[1]; startM[1] = start[2]; startM[2] = start[0];
    countM[0] = count[1]; countM[1] = count[2]; countM[2] = count[0];

    /* test CDF-1, 2, and 5 formats separately */
        /* create a new file */
    cmode = NC_CLOBBER;
    
 
    sprintf(fname, "%s.cdf%d",filename, NC_FORMAT_CLASSIC);
    err = ncmpi_create(MPI_COMM_WORLD, fname, cmode, info, &ncid);
    if (err != NC_NOERR) {
        printf("Error at line %d in %s: ncmpi_create() file %s (%s)\n",
        __LINE__,__FILE__,fname,ncmpi_strerror(err));
        MPI_Abort(MPI_COMM_WORLD, -1);
        exit(1);
    }

    /* define dimensions */
    err = ncmpi_def_dim(ncid, "nprocs", nprocs,   &dimids[0]); CHECK_ERR
    err = ncmpi_def_dim(ncid, "Z",      gsize[0], &dimids[0]); CHECK_ERR
    err = ncmpi_def_dim(ncid, "Y",      gsize[1], &dimids[1]); CHECK_ERR
    err = ncmpi_def_dim(ncid, "X",      gsize[2], &dimids[2]); CHECK_ERR
    err = ncmpi_enddef(ncid);


    nerrs += non_blocking_put_schar(rank, ncid, dimids, start, count,
             startS, countS, stride, startM, countM, imap, buf);
    nerrs += non_blocking_put_short(rank, ncid, dimids, start, count,
             startS, countS, stride, startM, countM, imap, buf);
    nerrs += non_blocking_put_int(rank, ncid, dimids, start, count,
             startS, countS, stride, startM, countM, imap, buf);
    nerrs += non_blocking_put_long(rank, ncid, dimids, start, count,
             startS, countS, stride, startM, countM, imap, buf);
    nerrs += non_blocking_put_float(rank, ncid, dimids, start, count,
             startS, countS, stride, startM, countM, imap, buf);
    nerrs += non_blocking_put_double(rank, ncid, dimids, start, count,
             startS, countS, stride, startM, countM, imap, buf);
    /* wait for all input */
    //err = ncmpi_wait_all(ncid, NC_REQ_ALL, NULL, NULL);
    //CHECK_ERR

    /* close the file */
    err = ncmpi_close(ncid);
    CHECK_ERR

        /* create a new file */
    cmode = NC_CLOBBER;
    cmode |= NC_64BIT_OFFSET;
 
    sprintf(fname, "%s.cdf%d",filename, NC_FORMAT_64BIT_OFFSET);
    err = ncmpi_create(MPI_COMM_WORLD, fname, cmode, info, &ncid);
    if (err != NC_NOERR) {
        printf("Error at line %d in %s: ncmpi_create() file %s (%s)\n",
        __LINE__,__FILE__,fname,ncmpi_strerror(err));
        MPI_Abort(MPI_COMM_WORLD, -1);
        exit(1);
    }

    /* define dimensions */
    err = ncmpi_def_dim(ncid, "nprocs", nprocs,   &dimids[0]); CHECK_ERR
    err = ncmpi_def_dim(ncid, "Z",      gsize[0], &dimids[0]); CHECK_ERR
    err = ncmpi_def_dim(ncid, "Y",      gsize[1], &dimids[1]); CHECK_ERR
    err = ncmpi_def_dim(ncid, "X",      gsize[2], &dimids[2]); CHECK_ERR
    err = ncmpi_enddef(ncid);


    nerrs += non_blocking_put_schar(rank, ncid, dimids, start, count,
             startS, countS, stride, startM, countM, imap, buf);
    nerrs += non_blocking_put_short(rank, ncid, dimids, start, count,
             startS, countS, stride, startM, countM, imap, buf);
    nerrs += non_blocking_put_int(rank, ncid, dimids, start, count,
             startS, countS, stride, startM, countM, imap, buf);
    nerrs += non_blocking_put_long(rank, ncid, dimids, start, count,
             startS, countS, stride, startM, countM, imap, buf);
    nerrs += non_blocking_put_float(rank, ncid, dimids, start, count,
             startS, countS, stride, startM, countM, imap, buf);
    nerrs += non_blocking_put_double(rank, ncid, dimids, start, count,
             startS, countS, stride, startM, countM, imap, buf);
    /* wait for all input */
    //err = ncmpi_wait_all(ncid, NC_REQ_ALL, NULL, NULL);
    //CHECK_ERR

    /* close the file */
    err = ncmpi_close(ncid);
    CHECK_ERR

        /* create a new file */
    cmode = NC_CLOBBER;
    cmode |= NC_64BIT_DATA;
 
    sprintf(fname, "%s.cdf%d",filename, NC_FORMAT_64BIT_DATA);
    err = ncmpi_create(MPI_COMM_WORLD, fname, cmode, info, &ncid);
    if (err != NC_NOERR) {
        printf("Error at line %d in %s: ncmpi_create() file %s (%s)\n",
        __LINE__,__FILE__,fname,ncmpi_strerror(err));
        MPI_Abort(MPI_COMM_WORLD, -1);
        exit(1);
    }

    /* define dimensions */
    err = ncmpi_def_dim(ncid, "nprocs", nprocs,   &dimids[0]); CHECK_ERR
    err = ncmpi_def_dim(ncid, "Z",      gsize[0], &dimids[0]); CHECK_ERR
    err = ncmpi_def_dim(ncid, "Y",      gsize[1], &dimids[1]); CHECK_ERR
    err = ncmpi_def_dim(ncid, "X",      gsize[2], &dimids[2]); CHECK_ERR
    err = ncmpi_enddef(ncid);


    nerrs += non_blocking_put_schar(rank, ncid, dimids, start, count,
             startS, countS, stride, startM, countM, imap, buf);
    nerrs += non_blocking_put_uchar(rank, ncid, dimids, start, count,
             startS, countS, stride, startM, countM, imap, buf);
    nerrs += non_blocking_put_short(rank, ncid, dimids, start, count,
             startS, countS, stride, startM, countM, imap, buf);
    nerrs += non_blocking_put_ushort(rank, ncid, dimids, start, count,
             startS, countS, stride, startM, countM, imap, buf);
    nerrs += non_blocking_put_int(rank, ncid, dimids, start, count,
             startS, countS, stride, startM, countM, imap, buf);
    nerrs += non_blocking_put_uint(rank, ncid, dimids, start, count,
             startS, countS, stride, startM, countM, imap, buf);
    nerrs += non_blocking_put_long(rank, ncid, dimids, start, count,
             startS, countS, stride, startM, countM, imap, buf);
    nerrs += non_blocking_put_float(rank, ncid, dimids, start, count,
             startS, countS, stride, startM, countM, imap, buf);
    nerrs += non_blocking_put_double(rank, ncid, dimids, start, count,
             startS, countS, stride, startM, countM, imap, buf);
    nerrs += non_blocking_put_longlong(rank, ncid, dimids, start, count,
             startS, countS, stride, startM, countM, imap, buf);
    nerrs += non_blocking_put_ulonglong(rank, ncid, dimids, start, count,
             startS, countS, stride, startM, countM, imap, buf);
    /* wait for all input */
    //err = ncmpi_wait_all(ncid, NC_REQ_ALL, NULL, NULL);
    //CHECK_ERR

    /* close the file */
    err = ncmpi_close(ncid);
    CHECK_ERR


    free(buf);
    MPI_Info_free(&info);

    /* check if PnetCDF freed all internal malloc */
    MPI_Offset malloc_size, sum_size;
    err = ncmpi_inq_malloc_size(&malloc_size);
    if (err == NC_NOERR) {
        MPI_Reduce(&malloc_size, &sum_size, 1, MPI_OFFSET, MPI_SUM, 0, MPI_COMM_WORLD);
        if (rank == 0 && sum_size > 0)
            printf("heap memory allocated by PnetCDF internally has %lld bytes yet to be freed\n",
                   sum_size);
    }

    MPI_Allreduce(MPI_IN_PLACE, &nerrs, 1, MPI_INT, MPI_SUM, MPI_COMM_WORLD);
    if (rank == 0) {
        if (nerrs) printf(FAIL_STR,nerrs);
        else       printf(PASS_STR);
    }

    MPI_Finalize();
    return (nerrs > 0);
}

