/* Do not edit this file. It is produced from the corresponding .m4 source */
/*********************************************************************
*
*  Copyright (C) 2017, Northwestern University and Argonne National Laboratory
*  See COPYRIGHT notice in top-level directory.
*
*********************************************************************/
/* $Id: ncmpilogdump.c 3078 2017-06-26 18:47Z khou $ */

#include <stdio.h>
#include <stdlib.h>
#include <common.h>
#include <mpi.h>

int main(int argc, char *argv[]) {
    int i;
    int rank, np;
    char outpath[1024];
    int decom;

    MPI_Init(&argc, &argv);
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);
    MPI_Comm_size(MPI_COMM_WORLD, &np);
    
    if(np > 1){
        if(rank == 0){
            printf("ncmpizip can only run on 1 process\n");
        }
        return 0;
    }

    if (argc < 2){
        printf("Usage: ./ncmpizip <NC File to Compress> [Options]\n");
        printf("\t\t -o <Output file>\n");
        printf("\t\t -d <Decompress>\n");
        return 0;
    }

    sprintf(outpath, "%s_zip.nc", argv[1]);
    decom = 0;

    for (i = 2; i < argc; i++){
        if (strcmp(argv[i], "-o") == 0){
            if (i + 1 < argc){
                sprintf(outpath, "%s", argv[++i]);
            }
            i++;
        }
        else if (strcmp(argv[i], "-d") == 0){
            decom = 1;
        }
    }

    if (decom){
        unzip(argv[1], outpath);
    }
    else{
        zip(argv[1], outpath);
    }

    MPI_Finalize();

    return 0;
}
